spring:
  datasource:
    username: root
    password: LstXyh123
    url: jdbc:mysql://rm-cn-27a3jaot8000e9co.rwlb.rds.aliyuncs.com:3306/self_study_room?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html